# By default, the version is set to "latest". This can be set to any version
# from 0.4.2 and above, but you MUST include the full version number.
# If you wish to increase the security releases automatically set the
# version to be 'X.Y', otherwise it will be 'X.Y.Z'.
version: 0.8.0
